- name: "Check if ambari-server is running"
  shell: /usr/bin/ps -ef | /usr/bin/grep -i ambari-server | /usr/bin/grep -v grep
  register: service_ambari_server_status
  ignore_errors: true

- name: "Add ambari repo"
  get_url:
    url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.0.0/ambari.repo
    dest: /etc/yum.repos.d/
    mode: 0644
  when: service_ambari_server_status.rc != 0

- name: "Install AMBARI-SERVER package"
  yum:
    name: ambari-server.x86_64
    state: latest
  when: service_ambari_server_status.rc != 0

- name: "Setup AMBARI-SERVER"
  expect:
    command: /usr/sbin/ambari-server setup
    responses:
      'OK to continue \[y\/n\] \(y\)\? ': "y"
      'Customize user account for ambari-server daemon \[y\/n\] \(n\)\? ': 'y'
      'Enter user account for ambari-server daemon \(root\):': 'ambari'
      'Enter choice \(1\):': '1'
      'Do you accept the Oracle Binary Code License Agreement \[y\/n\] \(y\)\? ': 'y'
      'Enable Ambari Server to download and install GPL Licensed LZO packages \[y\/n\] \(n\)\? ': 'y'
      'Enter advanced database configuration \[y\/n\] \(n\)\? ': 'n'
      'Change this setting \[y\/n\] \(n\)\? ': 'n'
      'Do you want to change Oracle JDK \[y\/n\] \(n\)\? ': 'n'
    echo: yes
  become: true
  when: service_ambari_server_status.rc != 0

- name: "Check if ambari-server is running"
  shell: /usr/bin/ps -ef | /usr/bin/grep -i ambari-server | /usr/bin/grep -v grep
  register: service_ambari_server_status2
  ignore_errors: true

- name: "Start AMBARI-SERVER"
  command: /usr/sbin/ambari-server start
  when: service_ambari_server_status2.rc != 0

# +INFO: https://docs.hortonworks.com/HDPDocuments/Ambari-2.6.2.2/bk_ambari-security/content/how_to_configure_ambari_server_for_non-root.html
#- name: "Configure Ambari Server for Non-Root User (ambari)"
# Add /etc/sudoers
# Ambari Commands
#ambari ALL=(ALL) NOPASSWD:SETENV: /bin/mkdir -p /etc/security/keytabs, /bin/chmod * /etc/security/keytabs/*.keytab, /bin/chown * /etc/security/keytabs/*.keytab, /bin/chgrp * /etc/security/keytabs/*.keytab, /bin/rm -f /etc/security/keytabs/*.keytab, /bin/cp -p -f /var/lib/ambari-server/data/tmp/* /etc/security/keytabs/*.keytab

# usermod -a -G hadoop ambari