- name: "Disable SElinux"
  selinux:
    state: disabled

- name: "Configure /etc/hosts file"
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: "Set timezone"
  timezone:
    name: Europe/Madrid

# Install pexpect requirement for 'expect' Ansible module
- name: "Install EPEL repo"
  yum:
    name: epel-release
    state: latest

- name: "Install python-pip"
  yum:
    name: python-pip
    state: latest

- name: "Upgrade python-pip"
  command: pip install --upgrade pip

- name: "Install pexpect"
  command: pip install pexpect==3.3

- name: "Install other packages"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - wget.x86_64
    - vim-common.x86_64
    - vim-enhanced.x86_64
    - unzip.x86_64

- name: "Reboot if required"
  shell: sleep 2 && shutdown -r now 'Reboot required' removes=/var/run/reboot-required
  become: true
  async: 1
  poll: 0
  ignore_errors: true

- name: "Wait for reboot"
  local_action: wait_for host=127.0.0.1 port=2222 delay=10 state=started
  become: false